//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLayer.ServicePessoa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaDto", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.Dto")]
    [System.SerializableAttribute()]
    public partial class PessoaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeCompletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((this.IdadeField.Equals(value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCompleto {
            get {
                return this.NomeCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCompletoField, value) != true)) {
                    this.NomeCompletoField = value;
                    this.RaisePropertyChanged("NomeCompleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePessoa.IServicePessoa")]
    public interface IServicePessoa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/BuscarPorCpf", ReplyAction="http://tempuri.org/IServicePessoa/BuscarPorCpfResponse")]
        WebLayer.ServicePessoa.PessoaDto BuscarPorCpf(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/BuscarPorCpf", ReplyAction="http://tempuri.org/IServicePessoa/BuscarPorCpfResponse")]
        System.Threading.Tasks.Task<WebLayer.ServicePessoa.PessoaDto> BuscarPorCpfAsync(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/BuscarPorCodigo", ReplyAction="http://tempuri.org/IServicePessoa/BuscarPorCodigoResponse")]
        WebLayer.ServicePessoa.PessoaDto BuscarPorCodigo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/BuscarPorCodigo", ReplyAction="http://tempuri.org/IServicePessoa/BuscarPorCodigoResponse")]
        System.Threading.Tasks.Task<WebLayer.ServicePessoa.PessoaDto> BuscarPorCodigoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/ListarPessoas", ReplyAction="http://tempuri.org/IServicePessoa/ListarPessoasResponse")]
        WebLayer.ServicePessoa.PessoaDto[] ListarPessoas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/ListarPessoas", ReplyAction="http://tempuri.org/IServicePessoa/ListarPessoasResponse")]
        System.Threading.Tasks.Task<WebLayer.ServicePessoa.PessoaDto[]> ListarPessoasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePessoaChannel : WebLayer.ServicePessoa.IServicePessoa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePessoaClient : System.ServiceModel.ClientBase<WebLayer.ServicePessoa.IServicePessoa>, WebLayer.ServicePessoa.IServicePessoa {
        
        public ServicePessoaClient() {
        }
        
        public ServicePessoaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePessoaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePessoaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePessoaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebLayer.ServicePessoa.PessoaDto BuscarPorCpf(string cpf) {
            return base.Channel.BuscarPorCpf(cpf);
        }
        
        public System.Threading.Tasks.Task<WebLayer.ServicePessoa.PessoaDto> BuscarPorCpfAsync(string cpf) {
            return base.Channel.BuscarPorCpfAsync(cpf);
        }
        
        public WebLayer.ServicePessoa.PessoaDto BuscarPorCodigo(int codigo) {
            return base.Channel.BuscarPorCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<WebLayer.ServicePessoa.PessoaDto> BuscarPorCodigoAsync(int codigo) {
            return base.Channel.BuscarPorCodigoAsync(codigo);
        }
        
        public WebLayer.ServicePessoa.PessoaDto[] ListarPessoas() {
            return base.Channel.ListarPessoas();
        }
        
        public System.Threading.Tasks.Task<WebLayer.ServicePessoa.PessoaDto[]> ListarPessoasAsync() {
            return base.Channel.ListarPessoasAsync();
        }
    }
}
