//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLayer.ServiceMedicamento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicamentoDto", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.Dto")]
    [System.SerializableAttribute()]
    public partial class MedicamentoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApresentacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClasseTerapeuticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apresentacao {
            get {
                return this.ApresentacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApresentacaoField, value) != true)) {
                    this.ApresentacaoField = value;
                    this.RaisePropertyChanged("Apresentacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClasseTerapeutica {
            get {
                return this.ClasseTerapeuticaField;
            }
            set {
                if ((object.ReferenceEquals(this.ClasseTerapeuticaField, value) != true)) {
                    this.ClasseTerapeuticaField = value;
                    this.RaisePropertyChanged("ClasseTerapeutica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Forma {
            get {
                return this.FormaField;
            }
            set {
                if ((object.ReferenceEquals(this.FormaField, value) != true)) {
                    this.FormaField = value;
                    this.RaisePropertyChanged("Forma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Processo {
            get {
                return this.ProcessoField;
            }
            set {
                if ((this.ProcessoField.Equals(value) != true)) {
                    this.ProcessoField = value;
                    this.RaisePropertyChanged("Processo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Registro {
            get {
                return this.RegistroField;
            }
            set {
                if ((this.RegistroField.Equals(value) != true)) {
                    this.RegistroField = value;
                    this.RaisePropertyChanged("Registro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMedicamento.IServiceMedicamento")]
    public interface IServiceMedicamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMedicamento/BuscarPorCodigo", ReplyAction="http://tempuri.org/IServiceMedicamento/BuscarPorCodigoResponse")]
        WebLayer.ServiceMedicamento.MedicamentoDto BuscarPorCodigo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMedicamento/BuscarPorCodigo", ReplyAction="http://tempuri.org/IServiceMedicamento/BuscarPorCodigoResponse")]
        System.Threading.Tasks.Task<WebLayer.ServiceMedicamento.MedicamentoDto> BuscarPorCodigoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMedicamento/ListarMedicamentos", ReplyAction="http://tempuri.org/IServiceMedicamento/ListarMedicamentosResponse")]
        WebLayer.ServiceMedicamento.MedicamentoDto[] ListarMedicamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMedicamento/ListarMedicamentos", ReplyAction="http://tempuri.org/IServiceMedicamento/ListarMedicamentosResponse")]
        System.Threading.Tasks.Task<WebLayer.ServiceMedicamento.MedicamentoDto[]> ListarMedicamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMedicamento/SalvarMedicamento", ReplyAction="http://tempuri.org/IServiceMedicamento/SalvarMedicamentoResponse")]
        void SalvarMedicamento(WebLayer.ServiceMedicamento.MedicamentoDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMedicamento/SalvarMedicamento", ReplyAction="http://tempuri.org/IServiceMedicamento/SalvarMedicamentoResponse")]
        System.Threading.Tasks.Task SalvarMedicamentoAsync(WebLayer.ServiceMedicamento.MedicamentoDto pessoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMedicamentoChannel : WebLayer.ServiceMedicamento.IServiceMedicamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMedicamentoClient : System.ServiceModel.ClientBase<WebLayer.ServiceMedicamento.IServiceMedicamento>, WebLayer.ServiceMedicamento.IServiceMedicamento {
        
        public ServiceMedicamentoClient() {
        }
        
        public ServiceMedicamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMedicamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMedicamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMedicamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebLayer.ServiceMedicamento.MedicamentoDto BuscarPorCodigo(int codigo) {
            return base.Channel.BuscarPorCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<WebLayer.ServiceMedicamento.MedicamentoDto> BuscarPorCodigoAsync(int codigo) {
            return base.Channel.BuscarPorCodigoAsync(codigo);
        }
        
        public WebLayer.ServiceMedicamento.MedicamentoDto[] ListarMedicamentos() {
            return base.Channel.ListarMedicamentos();
        }
        
        public System.Threading.Tasks.Task<WebLayer.ServiceMedicamento.MedicamentoDto[]> ListarMedicamentosAsync() {
            return base.Channel.ListarMedicamentosAsync();
        }
        
        public void SalvarMedicamento(WebLayer.ServiceMedicamento.MedicamentoDto pessoa) {
            base.Channel.SalvarMedicamento(pessoa);
        }
        
        public System.Threading.Tasks.Task SalvarMedicamentoAsync(WebLayer.ServiceMedicamento.MedicamentoDto pessoa) {
            return base.Channel.SalvarMedicamentoAsync(pessoa);
        }
    }
}
